function get_wlf(root, model_sets)

[model_names, wlf, wake_length, mesh_density, decay_to, simulation_time] = extract_all_wlf(root, model_sets);
for kfn = 1:size(model_names,1)
    for nfe = 1:size(model_names,2)
        disp([model_names{kfn, nfe}, ' ', num2str(wlf(kfn, nfe) *1E-9),...
            'mV/pC Wakelength ', num2str(wake_length(kfn, nfe)),...
            ' Decay level: ', num2str(decay_to(kfn, nfe)), ...
            ' Simulation time: ', num2str(simulation_time(kfn, nfe)), 's ',...
            ' Mesh density: ', num2str(mesh_density(kfn, nfe))])
    end %for
end %for