function ov = generate_latex_for_wake_analysis(wake_data, mi, ppi, results_paths)
% Generates latex code based on the wake simulation results.
%
% wake_data(stuct): Results of the analysis.
% mi(struct): Information in input setup.
% ppi(struct): Information on postprocessing settings
% results_paths(struct): Paths to get the images from and to put the resulting
%                        documentation.
% ov is the output latex code.
%
% Example: ov = generate_latex_for_wake_analysis(wake_data, mi, ppi, results_paths)


% Generates a latex document
ov = cell(1,1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\chapter{Wakefield analysis}');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Losses}');

ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,['\includegraphics [width=0.9\textwidth]{',fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'Thermal_Losses_into_materials.eps']),'}']);
ov = cat(1,ov,'\caption{Energy lost into different structural elements.}');
ov = cat(1,ov,'\end{figure}');

ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Wakes}');
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'wake_potential.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'longditudinal_real_wake_impedance.eps']),...
    'Wake potential over time. If the model is of appropriate wake length, then the wake potential should decay to zero (or nearly so).',...
    'Real wake impedance.');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\clearpage');
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'transverse_dipole_x_wake_potential.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'transverse_dipole_y_wake_potential.eps']),...
    'Transverse wake potential in X axis. This is usually only significant if the beam is offset in x.',...
    'Transverse wake potential in Y axis. This is usually only significant if the beam is offset in y.');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'transverse_x_real_wake_impedance.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'transverse_y_real_wake_impedance.eps']),...
    'Transverse wake impedance in X axis. This is usually only significant if the beam is offset in x.',...
    'Transverse wake impedance in Y axis. This is usually only significant if the beam is offset in y.');
ov = cat(1,ov,ov1);

ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Resonances}');
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'Q_from_wake.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'R_over_Q_from_wake.eps']),...
    'Q.',...
    '$\frac{R}{Q}$.');
ov = cat(1,ov,ov1);

ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Ports}');
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'port_signals.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'port_signals_first4ns.eps']),...
    'Port signals.',...
    'Port signals (first 4ns).');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'port_mode_signals.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'port_mode_signals_first4ns.eps']),...
    'Port mode signals.',...
    'Port mode signals (first 4ns).');
ov = cat(1,ov,ov1);
for hsd = 1:length(wake_data.port.labels)
ov1 = latex_side_by_side_images(fullfile(results_paths.postprocessing_plotting_path,...
    ['Frequency_vs_Mode_for_port_', wake_data.port.labels{hsd}, '.eps']),...
    fullfile(results_paths.postprocessing_plotting_path,...
    ['Time_vs_Mode_for_port_', wake_data.port.labels{hsd}, '.eps']),...
    ['Frequency vs Mode for port "', regexprep(wake_data.port.labels{hsd}, '_', ' ')],...
    ['Time vs Mode for port ', regexprep(wake_data.port.labels{hsd}, '_', ' ')]);
ov = cat(1,ov,ov1);
end %for
ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Voltage monitors}');
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'voltage_monitors.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'voltage_monitors_first4ns.eps']),...
    'Voltage monitors',...
    'Voltage monitors (first 4ns).');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Checks}');

ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,['\includegraphics [width=0.9\textwidth]{',fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'Energy.eps']),'}']);
ov = cat(1,ov,'\caption{Energy in the structure.}');
ov = cat(1,ov,'\end{figure}');
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'input_signal_alignment_check.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'input_signal_lossy_reactive_check.eps']),...
    'Alignment check',...
    'Lossy vs reactive signal check');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images(fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'bunch_spectrum.eps']),...
    fullfile(results_paths.analysis_plotting_path,...
    [mi.base_model_name, 'charge_distribution.eps']),...
    'Bunch spectrum',...
    'Charge distribution');
ov = cat(1,ov,ov1);
