function ov = generate_latex_for_wake_analysis(alpha, beta, cutoff, port_labels)
% Generates latex code based on the wake simulation results.
%
% alpha is
% beta is
% cutoff is
% port_labels is
% ov is the output latex code.
%
% Example: ov = generate_latex_for_wake_analysis(alpha, beta, cutoff, port_labels)

% Generates a latex document
ov = cell(1,1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\chapter{Wakefield analysis}');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Losses}');
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\includegraphics [width=0.95\textwidth]{summary.eps}');
ov = cat(1,ov,'\caption{Summary}');
ov = cat(1,ov,'\end{figure}');

ov1 = latex_side_by_side_images('Thermal_Losses_within_the_structure.eps',...
    'Thermal_Fractional_Losses_distribution_within_the_structure.eps',...
    'Energy loss', 'Relative Energy loss');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\includegraphics [width=0.48\textwidth]{Material_loss_over_time.eps}');
ov = cat(1,ov,'\caption{Energy lost into different structural elements.}');
ov = cat(1,ov,'\end{figure}');
% ov1 = latex_side_by_side_images('Material_loss_over_time.eps',...
%     'Fractional_material_loss_over_time.eps',...
%     'Energy lost into different structural elements.',...
%     'Fraction of total energy lost into individual structural components.');
% ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('cumulative_total_energy.eps',...
    'cumulative_energy.eps',...
    'Time evolution of energy lost into all ports.',...
    'Time evolution of energy lost into each port.');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Wakes}');
ov1 = latex_side_by_side_images('wake_potential.eps',...
    'longditudinal_real_wake_impedance.eps',...
    'Wake potential over time.',...
    'Longditudinal real wake impedance.');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\caption{Longditudinal imaginary wake impedance.}');
ov = cat(1,ov,'\includegraphics [width=0.48\textwidth]{longditudinal_imaginary_wake_impedance.eps}');
ov = cat(1,ov,'\end{figure}');
ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Ports}');
ov1 = latex_side_by_side_images('dominant_port_signals.eps',...
    'port_signals.eps',...
    'Comparison of raw and processed signals on the dominant mode of each port.',...
    'All modes on each port.');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('Energy_loss_distribution_of_bunch__and_energy_seen_at_ports.eps',...
    'cumulative_Energy_loss_distribution_of_bunch__and_energy_seen_at_ports.eps',...
    'Energy loss spectrum from the bunch, and out of ports.',...
    'Cumulative sum of energy lost from bunch and out of ports.');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('Energy_loss_distribution_of_bunch__and_energy_seen_at_ports_f_zoom.eps',...
    'cumulative_Energy_loss_distribution_of_bunch__and_energy_seen_at_ports_f_zoom.eps',...
    ' ',' ');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('Energy_left_in_structure.eps',...
    'cumulative_Energy_left_in_structure.eps',...
    'Difference between energy lost from bunch into structure, and energy emitted out of the ports.',...
    'Cumulative sum of energy into and out of structure.');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('Energy_left_in_structure_f_zoom.eps',...
    'cumulative_Energy_left_in_structure_f_zoom.eps',...
    ' ',' ');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('energy_loss_port_types.eps',...
    'cumulative_energy_loss_port_types.eps',...
    'Spectra ','Cumulative sums');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('energy_loss_distribution_ports.eps',...
    'cumulative_energy_loss_distribution_ports.eps',...
    'Port signals on a per frequency basis for different port types.',' ');
ov = cat(1,ov,ov1);
ov = cat(1,ov,generate_wg_cutoff_table(alpha, beta, cutoff, port_labels));
ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Multibunch extrapolation}');
ov = cat(1,ov,['All the results presented so far are for a single passage of a single bunch. '...
    'However, in Diamond we have a bunch train which repeatedly passes through the structure '...
    'This generates much fine structure in the Fourier transform of the bunch structure, '...
    'which means that the sensitivity to the wake impedance is enhanced at some frequencies and suppressed in others.']);
ov = cat(1,ov,' ');
ov = cat(1,ov,'The results in this chapter are an attempt to quantify the impact on machine parameters');
ov1 = latex_side_by_side_images('wake_impedance_vs_bunch_spectrum.eps',...
    'power_loss_for_analysis.eps',...
    'Showing the overlap of the bunch spectra and the wake impedance.',...
    'Power loss comparison for a scaled single bunch results and a full analysis.');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\includegraphics [width=0.40\textwidth]{wake_loss_factor_extrapolation_bunch_length.eps}');
ov = cat(1,ov,['\caption[Extrapolating the wake loss factor for longer bunches.]'...
    '{Extrapolating the wake loss factor for longer bunches.}']);
ov = cat(1,ov,'\end{figure}');
ov = cat(1,ov,'\clearpage');
ov = cat(1,ov,['In this case, the losses into the structure are infered from '...
    'the fraction of energy accounted for from emmission from the ports. '...
    'This will have a large error if the total energy accounted for in the '...
    'single bunch case is far from 100\%.']);
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\includegraphics [width=0.95\textwidth]{summary_multibunch.eps}');
ov = cat(1,ov,'\caption{Changes in losses due to machine changes}');
ov = cat(1,ov,'\end{figure}');
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\begin{center}');
ov = cat(1,ov,'\includegraphics [width=0.48\textwidth]{power_loss_for_different_machine_conditions.eps}');
ov = cat(1,ov,'\caption{Power loss for various machine parameters.}');
ov = cat(1,ov,'\end{center}');
ov = cat(1,ov,'\end{figure}');
ov = cat(1,ov,'\clearpage');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ov = cat(1,ov,'\section{Simulation verification}');
ov = cat(1,ov,['By truncating the wake potential by differing amounts, '...
    'and rerunning the post processing, it is possible to determine if '...
    'the model has been run long enough to generate stable output.']);
ov = cat(1,ov,'Simulation stablisation');
ov1 = latex_side_by_side_images('sweep_Q.eps',...
    'sweep_mag.eps',...
    'Q evolution over wake length',...
    'Peak magnitude evolution over wake length');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('sweep_bw.eps',...
    'sweep_freqs.eps',...
    'Bandwidth evolution over wake length',...
    'Peak frequency evolution over wake length');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\clearpage');
ov = cat(1,ov,['By using a block FFT on the wake potential, one can '...
    'determine the  magnitude of the peaks at different parts of the '...
    'ring down. This also allows an alternative measure of Q for those '...
    'resonances still identifible at the end of hte simulation.']);
ov1 = latex_side_by_side_images('time_slices_blockfft.eps',...
    'time_slices_endfft.eps',...
    'Peak magnitude evolution at different time slices',...
    'Spectrum of final time slice');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\includegraphics [width=0.48\textwidth]{time_slices_trend.eps}');
ov = cat(1,ov,'\caption{Trend of main peaks in final time slice over all time slices}');
ov = cat(1,ov,'\end{figure}');

ov1 = latex_side_by_side_images('energy_in_port_modes.eps',...
    'Energy.eps',...
    'Show the energy in the port modes. This is to make sure that enough modes were used in the simulation.',...
    'Check that the energy always decays (there can be a small rise as the bunch passes through the structure due to volume changes).');
ov = cat(1,ov,ov1);
ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\includegraphics [width=0.95\textwidth]{wake_impedance_vs_bunch_spectra.eps}');
ov = cat(1,ov,'\caption{Showing the overlap of the bunch spectra and the wake impedance.}');
ov = cat(1,ov,'\end{figure}');

ov = cat(1,ov,'\begin{figure}[htb]');
ov = cat(1,ov,'\centering');
ov = cat(1,ov,'\includegraphics [width=0.48\textwidth]{input_signal_alignment_check.eps}');
ov = cat(1,ov,'\caption{ }');
ov = cat(1,ov,'\end{figure}');

ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('beam_cumsum_check.eps',...
    'port_cumsum_check.eps',...
    ' ',' ');
ov = cat(1,ov,ov1);
ov1 = latex_side_by_side_images('input_signal_lossy_reactive_check.eps',...
    'tstart_check.eps',...
    ' ','Start of integration window');
ov = cat(1,ov,ov1);
if exist('Data_rate_vs_num_cores.eps','file')
    ov = cat(1,ov,'\begin{figure}[htb]');
    ov = cat(1,ov,'\centering');
    ov = cat(1,ov,['\includegraphics [width=0.48\textwidth]{','Data_rate_vs_num_cores.eps}']);
    ov = cat(1,ov,'\caption{Speed of calculation vs number of cores}');
    ov = cat(1,ov,'\end{figure}');
end
ov = cat(1,ov,'\clearpage');