function add_data_to_sparameter_graph(x_data, y_data, mode, lines, cols, linewidth, reciever_port_number, excitation_port_number, port_names)
hold on
plot(x_data, y_data,...
    'Linestyle',lines{rem(reciever_port_number,length(lines))+1},...
    'Color', cols{rem(excitation_port_number,length(cols))+1},...
    'LineWidth',  linewidth,...
    'DisplayName', strcat(regexprep(port_names{excitation_port_number}, '_', ' '),...
    '->', regexprep(port_names{reciever_port_number}, '_', ' '), ...
    ' S',num2str(reciever_port_number), num2str(excitation_port_number), '(',num2str(mode),')'));
hold off
end %function
