function min_y = add_data_to_sparameter_graph(x_data, y_data, mode, min_y, lines, cols, linewidth, n, exitation_port_number)
hold on
if min(y_data) < min_y
    min_y = min(y_data);
end %if
plot(x_data, y_data,...
    'Linestyle',lines{rem(n,length(lines))+1},...
    'Color', cols{rem(exitation_port_number,length(cols))+1},...
    'LineWidth',  linewidth,...
    'DisplayName', strcat('S',num2str(n), num2str(exitation_port_number), '(',num2str(mode),')'));
hold off
end %function
