function z_field = GdfidL_find_output_eigenmode(data_loc)
% finds the output generated by GdfidL and returns the paths for the different
% result types
%
% Example: [ WP_l, Port_mat, port_names, Energy, Energy_in_ceramics] = GdfidL_find_ouput(data_loc)

%
% Run name is the name prepended to the results by GdfidL.
% data loc is the path to the scratch location where the results files are
% stored.

% get the full list of files in the scratch directory.
run_list = dir_list_gen(data_loc, '',1);

% % select only the results which contain the run name.
% inds = find_position_in_cell_lst(strfind(full_list, [run_name,'_scratch']));
% run_list = full_list(inds);
% clear full_list

% now find the londitudinal field on axis files.
inds = find_position_in_cell_lst(strfind(run_list, 'lineplot-nr'));
z_field = run_list(inds);

